#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\$request_uri;
    }
}
EOF'

# Restart Nginx
sudo service nginx restart
